/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './boaster.module';
import * as i2 from '@angular/common';
import * as i3 from './boaster.service';
export const BoasterModuleNgFactory:i0.NgModuleFactory<i1.BoasterModule> = i0.ɵcmf(i1.BoasterModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BoasterService,
          i3.BoasterService,([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i1.BoasterModule,i1.BoasterModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hcmMuZXJuc3QvX2JzX3Byb2plY3RzL25nMi1ib2FzdGVyL2JvYXN0ZXIvYm9hc3Rlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWFyYy5lcm5zdC9fYnNfcHJvamVjdHMvbmcyLWJvYXN0ZXIvYm9hc3Rlci9ib2FzdGVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
