/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './boaster.component';
import * as i3 from './boaster.service';
const styles_BoasterComponent:any[] = ([] as any[]);
export const RenderType_BoasterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BoasterComponent,data:{'animation':[{type:7,name:'itemAnim',definitions:[{type:1,
        expr:':enter',animation:[{type:6,styles:{transform:'translateY(50px)'},offset:(null as any)},
            {type:4,styles:(null as any),timings:350}],options:(null as any)},{type:1,
        expr:':leave',animation:[{type:3,steps:[{type:4,styles:{type:6,styles:{transform:'translateY(-10px)'},
            offset:(null as any)},timings:'0.5s ease'},{type:4,styles:{type:6,styles:{opacity:0},
            offset:(null as any)},timings:'0.5s 0.2s ease'}],options:(null as any)}],
        options:(null as any)}],options:{}}]}});
function View_BoasterComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'button',[['class',
      'close'],['type','button']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),
      i0.ɵeld(2,0,(null as any),(null as any),1,'span',[['aria-hidden','true']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['×'])),(_l()(),i0.ɵted(-1,(null as any),['\n        ']))],(null as any),
      (null as any));
}
function View_BoasterComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),7,'div',[['role',
      'alert']],[[24,'@itemAnim',0],[8,'className',0]],[[(null as any),'click']],(_v,
      en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.dismiss(_v.context.$implicit)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_BoasterComponent_2)),
      i0.ɵdid(3,16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],
          {ngIf:[0,'ngIf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),1,'div',[['class','toast-icon']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵeld(6,0,(null as any),(null as any),0,'img',[['src','./assets/images/appguard-v2.1.png']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(7,(null as any),['\n        ','\n    ']))],(_ck,_v) => {
    const currVal_2:any = _v.context.$implicit.userMustDismiss;
    _ck(_v,3,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = (undefined as any);
    const currVal_1:any = i0.ɵinlineInterpolate(1,'alert alert-',_v.context.$implicit.msgType,
        '');
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.msg;
    _ck(_v,7,0,currVal_3);
  });
}
export function View_BoasterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_BoasterComponent_1)),i0.ɵdid(3,802816,
          (null as any),0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i2.BoasterComponent = _v.component;
    const currVal_1:any = _co.toastSrv.getMessages();
    _ck(_v,3,0,currVal_1);
  },(_ck,_v) => {
    var _co:i2.BoasterComponent = _v.component;
    const currVal_0:any = i0.ɵinlineInterpolate(2,'alert-container alert-position-',
        _co.toastSrv.config.vertical,' alert-position-',_co.toastSrv.config.horizontal,
        '');
    _ck(_v,0,0,currVal_0);
  });
}
export function View_BoasterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-toast',
      ([] as any[]),(null as any),(null as any),(null as any),View_BoasterComponent_0,
      RenderType_BoasterComponent)),i0.ɵdid(1,114688,(null as any),0,i2.BoasterComponent,
      [i3.BoasterService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BoasterComponentNgFactory:i0.ComponentFactory<i2.BoasterComponent> = i0.ɵccf('app-toast',
    i2.BoasterComponent,View_BoasterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hcmMuZXJuc3QvX2JzX3Byb2plY3RzL25nMi1ib2FzdGVyL2JvYXN0ZXIvYm9hc3Rlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWFyYy5lcm5zdC9fYnNfcHJvamVjdHMvbmcyLWJvYXN0ZXIvYm9hc3Rlci9ib2FzdGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL21hcmMuZXJuc3QvX2JzX3Byb2plY3RzL25nMi1ib2FzdGVyL2JvYXN0ZXIvYm9hc3Rlci50ZW1wbGF0ZS5odG1sIiwibmc6Ly8vVXNlcnMvbWFyYy5lcm5zdC9fYnNfcHJvamVjdHMvbmcyLWJvYXN0ZXIvYm9hc3Rlci9ib2FzdGVyLmNvbXBvbmVudC50cy5Cb2FzdGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImFsZXJ0LWNvbnRhaW5lciBhbGVydC1wb3NpdGlvbi17e3RvYXN0U3J2LmNvbmZpZy52ZXJ0aWNhbH19IGFsZXJ0LXBvc2l0aW9uLXt7dG9hc3RTcnYuY29uZmlnLmhvcml6b250YWx9fVwiPlxuICAgIDxkaXYgW0BpdGVtQW5pbV0gY2xhc3M9XCJhbGVydCBhbGVydC17e21zZy5tc2dUeXBlfX1cIiAqbmdGb3I9XCJsZXQgbXNnIG9mIHRvYXN0U3J2LmdldE1lc3NhZ2VzKCk7XCIgcm9sZT1cImFsZXJ0XCJcbiAgICAgICAgIChjbGljayk9XCJkaXNtaXNzKG1zZylcIj5cbiAgICAgICAgPGJ1dHRvbiAqbmdJZj1cIm1zZy51c2VyTXVzdERpc21pc3NcIiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJjbG9zZVwiPlxuICAgICAgICAgICAgPHNwYW4gYXJpYS1oaWRkZW49XCJ0cnVlXCI+JnRpbWVzOzwvc3Bhbj5cbiAgICAgICAgPC9idXR0b24+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJ0b2FzdC1pY29uXCI+PGltZyBzcmM9XCIuL2Fzc2V0cy9pbWFnZXMvYXBwZ3VhcmQtdjIuMS5wbmdcIi8+PC9kaXY+XG4gICAgICAgIHt7bXNnLm1zZ319XG4gICAgPC9kaXY+XG48L2Rpdj4iLCI8YXBwLXRvYXN0PjwvYXBwLXRvYXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDR1E7TUFBQTtNQUFBLGdCQUFnRSxzREFDNUQ7YUFBQTtVQUFBLDBEQUF5QjtNQUFBLHNCQUFjOzs7O29CQUgvQztNQUFBO2VBQUE7SUFBQTtJQUFBO0lBQ0s7TUFBQTtNQUFBO0lBQUE7SUFETDtFQUFBLGdDQUM0QjtNQUN4QjthQUFBO1VBQUEsaUNBRVM7TUFDVDtVQUFBO01BQXdCO1VBQUE7TUFBb0Q7SUFIcEU7SUFBUixXQUFRLFNBQVI7O0lBRkM7SUFBWTtRQUFBO0lBQWpCLFdBQUssVUFBWSxTQUFqQjtJQUtnRjtJQUFBOzs7O29CQU5wRjtNQUFBO01BQXVILDhDQUNuSDtVQUFBLCtEQUFBO1VBQUE7VUFBQSx1Q0FPTTtVQUFBOztJQVArQztJQUFyRCxXQUFxRCxTQUFyRDs7O0lBREM7UUFBQTtRQUFBO0lBQUwsV0FBSyxTQUFMOzs7O29CQ0FBO01BQUE7aUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
